// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgramDesigner.Infrastructure.DbContexts;

#nullable disable

namespace ProgramDesigner.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720181526_First Mig")]
    partial class FirstMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProgramDesigner.Domain.Entities.ProgramEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("RootGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RootGroupId")
                        .IsUnique()
                        .HasFilter("[RootGroupId] IS NOT NULL");

                    b.ToTable("Programs", (string)null);
                });

            modelBuilder.Entity("ProgramDesigner.Domain.Entities.ProgramNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrerequisiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.HasIndex("PrerequisiteId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Nodes", (string)null);

                    b.HasDiscriminator().HasValue("ProgramNode");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProgramDesigner.Domain.Entities.Group", b =>
                {
                    b.HasBaseType("ProgramDesigner.Domain.Entities.ProgramNode");

                    b.Property<int?>("PickCount")
                        .HasColumnType("int");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Group");
                });

            modelBuilder.Entity("ProgramDesigner.Domain.Entities.Step", b =>
                {
                    b.HasBaseType("ProgramDesigner.Domain.Entities.ProgramNode");

                    b.HasDiscriminator().HasValue("Step");
                });

            modelBuilder.Entity("ProgramDesigner.Domain.Entities.ProgramEntity", b =>
                {
                    b.HasOne("ProgramDesigner.Domain.Entities.Group", null)
                        .WithMany("Parents")
                        .HasForeignKey("GroupId");

                    b.HasOne("ProgramDesigner.Domain.Entities.Group", "RootGroup")
                        .WithOne()
                        .HasForeignKey("ProgramDesigner.Domain.Entities.ProgramEntity", "RootGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RootGroup");
                });

            modelBuilder.Entity("ProgramDesigner.Domain.Entities.ProgramNode", b =>
                {
                    b.HasOne("ProgramDesigner.Domain.Entities.Group", "ParentGroup")
                        .WithMany("Children")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProgramDesigner.Domain.Entities.ProgramNode", "Prerequisite")
                        .WithMany()
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProgramDesigner.Domain.Entities.ProgramEntity", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentGroup");

                    b.Navigation("Prerequisite");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("ProgramDesigner.Domain.Entities.Group", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Parents");
                });
#pragma warning restore 612, 618
        }
    }
}
